version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --production
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - index.js
    - modules/*
    - modules/**/*
    - conf.json
    - node_modules/**/*
    - packacge.json
    - Procfile
    - .npmrc